### ISSUE TITLE
Mobile view is not responsive

### ISSUE THREAD

**Issue by iqbaladinur** [agitnaeta/tampolin#1]
Here the view from my phone:
OS: android pie
Browser: chrome 78.xxx
Resolution: (424x848) px

![Screenshot_20191117-093110](https://user-images.githubusercontent.com/18280154/69002227-41bf9e80-091d-11ea-9afe-6920ea7ef2ef.png)

I like your webapp, i hope you can make it mobile friendly 😁

**Comment by agitnaeta** [comment]
Thanks for your support, we finally fix this morning you can try it again
